title: phunatix' developer blog
author: Olaf Ngo
email: dev@ngo.lu
description: This is the code space of phunatix on GitHub
theme: jekyll-theme-slate

# social links
github_username:  phunatix
twitter_username: OlafAtScale

show_excerpts: true # set to false to remove excerpts on the homepage
