title: Olaf Ngo's developer blog
author: Olaf Ngo
email: dev@ngo.lu
description: > # this means to ignore newlines until "baseurl:"
  This is the code space of phunatix on GitHub
theme: minima

# social links
github_username:  phunatix

show_excerpts: true # set to false to remove excerpts on the homepage
